[package]
name = "crumpet"
description = "A pragmatic TPM 2.0 library with an easy to use api."
version = "0.1.3"
edition = "2024"
authors = ["hitesh.jasani@gmail.com"]
license = "MIT or Apache-2.0"
readme = "README.md"
repository = "https://github.com/hiteshjasani/crumpet"
categories = ["api-bindings", "cryptography", "hardware-support"]
keywords = ["tpm", "tpm2", "tss", "tbs"]

[features]
default = ["windows_dynamic"]
windows_dynamic = ["dep:libloading"]
windows_static = ["dep:windows", "dep:anyhow"]
mssim = []

[dependencies]
anyhow = { version = "1", optional = true }
libloading = { version = "0.8", optional = true }
rsa = "0.9"
sha2 = { version = "0.10", features = ["oid"] }
windows = { version = "0.62", optional = true, features = [
  "Win32_System_TpmBaseServices",
] }

[package.metadata.docs.rs]
# Disable building everything together
all-features = false
# Explicitly choose ONE valid default feature set for documentation
features = ["windows_dynamic"]
rustdoc-args = ["--cfg", "docsrs"]
