[package]
name = "examples_dynamic"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT or Apache 2.0"

[dev-dependencies]
crumpet = { path = "../crumpet", features = ["windows_dynamic"] }
rsa = "0.9"
sha2 = { version = "0.10", features = ["oid"] }

[[example]]
name = "dyn_create_context"
path = "dyn_create_context.rs"
