[package]
name = "examples_dynamic"
version = "0.1.0"
edition = "2024"
publish = false
authors = ["hitesh.jasani@gmail.com"]
license = "MIT or Apache-2.0"

[dev-dependencies]
crumpet = { path = "../crumpet", features = ["windows_dynamic"] }
rsa = "0.9"
sha2 = { version = "0.10", features = ["oid"] }

[[example]]
name = "dyn_create_context"
path = "dyn_create_context.rs"

[[example]]
name = "dyn_exp_ek_cert"
path = "dyn_exp_ek_cert.rs"

[[example]]
name = "dyn_cr_child_key"
path = "dyn_cr_child_key.rs"

[[example]]
name = "dyn_load_child_key"
path = "dyn_load_child_key.rs"
